In [3]:
import numpy as np

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 2]])

In [12]:
arr.shape

(2, 3)

In [13]:
arr.ndim

2

In [14]:
arr.size

6

In [15]:
a = np.array([1, 2, 3, 4])

In [16]:
a + 1

array([2, 3, 4, 5])

In [28]:
2 * a

array([2, 4, 6, 8])

In [29]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [30]:
np.power(a, 3)

array([ 1,  8, 27, 64], dtype=int32)

In [31]:
np.sum(a)

10

In [37]:
x = np.array([[1, 3], [2, 11]])
x

array([[ 1,  3],
       [ 2, 11]])

In [40]:
x.sum(axis=1)

array([ 4, 13])

1 = row - 0 = column

In [46]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[4,3]])
a

array([[1, 2],
       [3, 4]])

In [47]:
b

array([[1, 1],
       [4, 3]])

In [48]:
a == b

array([[ True, False],
       [False, False]])

In [49]:
np.array_equal(a, b)

False

In [50]:
arr_first = np.array([[1, 2, 3], [4, 5, 2]])

In [51]:
arr_sec = np.array([[1, 2, 3], [4, 5, 2]])


In [52]:
np.array_equal(arr_first, arr_sec)

True