In [1]:
import  numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [6]:
get = np.where(arr%2 ==0)
print(get)

(array([1, 3], dtype=int64),)


In [8]:
for x in get:
    print(arr[x])

[2 4]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [10]:
arr = np.array([3, 2, 0, 1])


In [13]:
print(np.sort(arr))

[0 1 2 3]


In [16]:
descending = arr[::-1]
print(descending)

[3 2 1 0]


In [17]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [18]:
arr = np.array([41, 42, 43, 44])


In [19]:
filtered = [False, True, False, False]

In [20]:
arr[filtered]

array([42])

In [21]:
arr = np.array([41, 42, 43, 44])

filter_arr = []

In [22]:
for element in arr:
    if(element == 42):
        filter_arr.append(True)
    else:
        filter_arr.append(False)

In [23]:
na = arr[filter_arr]

In [24]:
print(na)

[42]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [30]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
