In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,5])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
a = np.array(1)

In [7]:
b = np.array([1,23,4, 55,4])

In [9]:
c = np.array([[1,2],[12,2]])

In [10]:
d = np.array([[[12,2], [12,1]]])

In [11]:
print(a.ndim)

0


In [13]:
print(d.ndim)

3


In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


In [16]:
arr[0,4] + arr[1,4]

15

In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [18]:
arr[1,0,1]

8

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[3:]

array([4, 5, 6, 7])

In [22]:
arr[1:5:2]

array([2, 4])

In [23]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [37]:
arr[0, 1, 1:]

array([5, 6])

In [25]:
arr = np.array([1, 2, 3])


In [27]:
for x in arr:
    print(x)

1
2
3


In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [35]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
